{"app":"exunit_summarizer","classname":"Elixir.TestWithSummaryTest","describe":null,"describe_line":null,"failed":false,"file":"<ROOT>/test/exunit_summarizer_test.exs","line":20,"logs":"","message":"due to skip tag","name":"test one that skipped","skipped":true,"success":false,"test_type":"test","time":0}
{"app":"exunit_summarizer","classname":"Elixir.TestWithSummaryTest","describe":null,"describe_line":null,"failed":false,"file":"<ROOT>/test/exunit_summarizer_test.exs","line":8,"logs":"\u001b[33m[warn] This should not output\n\u001b[0m","name":"test one that passes","skipped":false,"success":true,"test_type":"test","time":0}
{"app":"exunit_summarizer","body":"  0) test one that fails when MAKE_TESTS_FAIL != \"\" (TestWithSummaryTest)\n     \u001b[1m\u001b[30mtest/exunit_summarizer_test.exs:13\u001b[0m\n     \u001b[31mAssertion with == failed\u001b[0m\n     \u001b[36mcode:  \u001b[0massert @should_fail == \"\"\n     \u001b[36mleft:  \u001b[0m\"\u001b[31mthis test intentionally fails\u001b[0m\"\n     \u001b[36mright: \u001b[0m\"\u001b[48;5;28m\u001b[0m\"\n     \u001b[36mstacktrace:\u001b[0m\n       test/exunit_summarizer_test.exs:16: (test)\n","classname":"Elixir.TestWithSummaryTest","describe":null,"describe_line":null,"failed":true,"file":"<ROOT>/test/exunit_summarizer_test.exs","line":13,"logs":"\u001b[33m[warn] This should output.\n\u001b[0m\u001b[31m[error] This should show an error.\n\u001b[0m","message":"Assertion with == failed","name":"test one that fails when MAKE_TESTS_FAIL != \"\"","skipped":false,"success":false,"test_type":"test","time":0}
{"app":"exunit_summarizer","classname":"Elixir.TestWithSummaryTest","describe":null,"describe_line":null,"failed":false,"file":"<ROOT>/test/exunit_summarizer_test.exs","line":24,"logs":"","name":"test slow test","skipped":false,"success":true,"test_type":"test","time":2}
{"app":"exunit_summarizer","classname":"Elixir.TestWithSummaryTest","describe":"a describe block","describe_line":30,"failed":false,"file":"<ROOT>/test/exunit_summarizer_test.exs","line":31,"logs":"","name":"test a describe block one that passes","skipped":false,"success":true,"test_type":"test","time":0}
{"app":"exunit_summarizer","body":"  0) test a describe block one that fails when MAKE_TESTS_FAIL != \"\" (TestWithSummaryTest)\n     \u001b[1m\u001b[30mtest/exunit_summarizer_test.exs:35\u001b[0m\n     \u001b[31mAssertion with == failed\u001b[0m\n     \u001b[36mcode:  \u001b[0massert @should_fail == \"\"\n     \u001b[36mleft:  \u001b[0m\"\u001b[31mthis test intentionally fails\u001b[0m\"\n     \u001b[36mright: \u001b[0m\"\u001b[48;5;28m\u001b[0m\"\n     \u001b[36mstacktrace:\u001b[0m\n       test/exunit_summarizer_test.exs:36: (test)\n","classname":"Elixir.TestWithSummaryTest","describe":"a describe block","describe_line":30,"failed":true,"file":"<ROOT>/test/exunit_summarizer_test.exs","line":35,"logs":"","message":"Assertion with == failed","name":"test a describe block one that fails when MAKE_TESTS_FAIL != \"\"","skipped":false,"success":false,"test_type":"test","time":0}
